//! Builtin trait system: `Builtin`, `FromArgs`, `CoerceArg`, and argument decoding helpers.

use super::{RError, RErrorKind, RValue};
use crate::interpreter::BuiltinContext;

/// Metadata for a trait-based builtin, generated by `#[derive(FromArgs)]`.
pub struct BuiltinInfo {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub min_args: usize,
    pub max_args: Option<usize>,
    pub doc: &'static str,
    /// Parameter names (from struct field names), for formals()/args().
    pub params: &'static [&'static str],
}

/// Decode R call arguments into a typed struct.
///
/// Implemented by `#[derive(FromArgs)]` on structs whose fields represent
/// R function parameters. Field names become R parameter names, field types
/// determine coercion, and `#[default(...)]` marks optional parameters.
pub trait FromArgs: Sized {
    /// Decode positional and named R arguments into Self.
    fn from_args(args: &[RValue], named: &[(String, RValue)]) -> Result<Self, RError>;

    /// Static metadata: parameter count, names, docs.
    fn info() -> &'static BuiltinInfo;
}

/// A trait-based builtin function.
///
/// Implementors define their arguments as a struct with `#[derive(FromArgs)]`,
/// then implement `Builtin::call` to execute the function body.
pub trait Builtin: FromArgs {
    /// Execute the builtin with decoded arguments.
    fn call(self, ctx: &BuiltinContext) -> Result<RValue, RError>;
}

/// Find an argument by name (with partial matching) or positional index.
pub fn find_arg<'a>(
    args: &'a [RValue],
    named: &'a [(String, RValue)],
    param_name: &str,
    positional_index: usize,
) -> Option<&'a RValue> {
    if let Some(v) = find_named_arg(named, param_name) {
        return Some(v);
    }
    // Positional fallback
    args.get(positional_index)
}

/// Find an argument by name only (exact match first, then unique partial match).
/// Used by the `FromArgs` derive macro with a runtime positional counter.
pub fn find_named_arg<'a>(named: &'a [(String, RValue)], param_name: &str) -> Option<&'a RValue> {
    // Exact name match first
    for (name, val) in named {
        if name == param_name {
            return Some(val);
        }
    }
    // Partial name match
    let candidates: Vec<_> = named
        .iter()
        .filter(|(name, _)| param_name.starts_with(name.as_str()))
        .collect();
    if candidates.len() == 1 {
        return Some(&candidates[0].1);
    }
    None
}

/// Coerce an RValue to a Rust type. Implemented for common R parameter types.
pub trait CoerceArg: Sized {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError>;
}

impl CoerceArg for f64 {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_double_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be numeric", param_name),
                )
            })
    }
}

impl CoerceArg for i64 {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_integer_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be an integer", param_name),
                )
            })
    }
}

impl CoerceArg for bool {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_logical_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be logical", param_name),
                )
            })
    }
}

impl CoerceArg for String {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_character_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be a character string", param_name),
                )
            })
    }
}

impl CoerceArg for RValue {
    fn coerce(val: &RValue, _param_name: &str) -> Result<Self, RError> {
        Ok(val.clone())
    }
}

/// Helper called by `FromArgs` derive-generated code.
pub fn coerce_arg<T: CoerceArg>(val: &RValue, param_name: &str) -> Result<T, RError> {
    T::coerce(val, param_name)
}
