//! Builtin trait system: `Builtin`, `FromArgs`, `CoerceArg`, and argument decoding helpers.
//!
//! R arguments have three states that matter: missing (not provided), NULL
//! (explicitly passed), or a value. This module models all three through the
//! [`RArg<T>`] enum and provides derive-friendly coercion traits.

use super::vector::Vector;
use super::{RError, RErrorKind, RValue};
use crate::interpreter::environment::Environment;
use crate::interpreter::BuiltinContext;

// region: RArg<T> — three-state R argument

/// The three states of an R function argument.
///
/// In R, `missing(x)` returns TRUE when the caller didn't provide `x` at all,
/// while `is.null(x)` returns TRUE when the caller explicitly passed NULL.
/// These are semantically different and many builtins branch on the distinction.
///
/// Use `RArg<T>` as a field type in `#[derive(FromArgs)]` structs when you need
/// the full three-way distinction. For simpler cases, use plain `T` (required)
/// or `Option<T>` (missing → None, NULL coerces or errors).
#[derive(Debug, Clone)]
pub enum RArg<T> {
    /// Caller did not provide this argument. `missing(x)` would return TRUE.
    Missing,
    /// Caller explicitly passed NULL.
    Null,
    /// Caller provided a value (possibly NA — that's inside T).
    Value(T),
}

impl<T> RArg<T> {
    pub fn is_missing(&self) -> bool {
        matches!(self, RArg::Missing)
    }

    pub fn is_null(&self) -> bool {
        matches!(self, RArg::Null)
    }

    pub fn value(&self) -> Option<&T> {
        match self {
            RArg::Value(v) => Some(v),
            _ => None,
        }
    }

    pub fn into_value(self) -> Option<T> {
        match self {
            RArg::Value(v) => Some(v),
            _ => None,
        }
    }

    /// Collapse both Missing and Null to None, Value to Some.
    pub fn optional(self) -> Option<T> {
        self.into_value()
    }

    /// Use a default when missing, but propagate NULL distinctly.
    pub fn or_default(self, default: T) -> Self {
        match self {
            RArg::Missing => RArg::Value(default),
            other => other,
        }
    }

    /// Unwrap to value, using `default` for both Missing and Null.
    pub fn unwrap_or(self, default: T) -> T {
        match self {
            RArg::Value(v) => v,
            _ => default,
        }
    }

    /// Unwrap to value, using `f()` for both Missing and Null.
    pub fn unwrap_or_else(self, f: impl FnOnce() -> T) -> T {
        match self {
            RArg::Value(v) => v,
            _ => f(),
        }
    }

    pub fn map<U>(self, f: impl FnOnce(T) -> U) -> RArg<U> {
        match self {
            RArg::Missing => RArg::Missing,
            RArg::Null => RArg::Null,
            RArg::Value(v) => RArg::Value(f(v)),
        }
    }
}

// endregion

// region: Dots — variadic argument capture

/// Captures all remaining positional arguments (`...` in R).
///
/// Use as a field type in `#[derive(FromArgs)]` structs for variadic builtins
/// like `c()`, `paste()`, `cat()`, `list()`, etc. Named arguments that match
/// other struct fields are consumed first; everything else goes into Dots.
#[derive(Debug, Clone, Default)]
pub struct Dots(pub Vec<RValue>);

impl Dots {
    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    pub fn iter(&self) -> std::slice::Iter<'_, RValue> {
        self.0.iter()
    }
}

impl IntoIterator for Dots {
    type Item = RValue;
    type IntoIter = std::vec::IntoIter<RValue>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}

impl<'a> IntoIterator for &'a Dots {
    type Item = &'a RValue;
    type IntoIter = std::slice::Iter<'a, RValue>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

// endregion

// region: Traits

/// Metadata for a trait-based builtin, generated by `#[derive(FromArgs)]`.
pub struct BuiltinInfo {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub min_args: usize,
    pub max_args: Option<usize>,
    pub doc: &'static str,
    /// Parameter names (from struct field names), for formals()/args().
    pub params: &'static [&'static str],
}

/// Decode R call arguments into a typed struct.
///
/// Implemented by `#[derive(FromArgs)]` on structs whose fields represent
/// R function parameters. Field names become R parameter names, field types
/// determine coercion, and `#[default(...)]` marks optional parameters.
///
/// Field type determines behavior:
/// - `T` — required, error if missing
/// - `Option<T>` — optional, `None` if missing
/// - `RArg<T>` — three-way: Missing / Null / Value
/// - `Dots` — captures remaining positional args
pub trait FromArgs: Sized {
    /// Decode positional and named R arguments into Self.
    fn from_args(args: &[RValue], named: &[(String, RValue)]) -> Result<Self, RError>;

    /// Static metadata: parameter count, names, docs.
    fn info() -> &'static BuiltinInfo;
}

/// A trait-based builtin function.
///
/// Implementors define their arguments as a struct with `#[derive(FromArgs)]`,
/// then implement `Builtin::call` to execute the function body.
pub trait Builtin: FromArgs {
    /// Execute the builtin with decoded arguments.
    fn call(self, ctx: &BuiltinContext) -> Result<RValue, RError>;
}

// endregion

// region: Argument lookup helpers

/// Find an argument by name (with partial matching) or positional index.
pub fn find_arg<'a>(
    args: &'a [RValue],
    named: &'a [(String, RValue)],
    param_name: &str,
    positional_index: usize,
) -> Option<&'a RValue> {
    if let Some(v) = find_named_arg(named, param_name) {
        return Some(v);
    }
    // Positional fallback
    args.get(positional_index)
}

/// Find an argument by name only (exact match first, then unique partial match).
/// Used by the `FromArgs` derive macro with a runtime positional counter.
pub fn find_named_arg<'a>(named: &'a [(String, RValue)], param_name: &str) -> Option<&'a RValue> {
    // Exact name match first
    for (name, val) in named {
        if name == param_name {
            return Some(val);
        }
    }
    // Partial name match
    let candidates: Vec<_> = named
        .iter()
        .filter(|(name, _)| param_name.starts_with(name.as_str()))
        .collect();
    if candidates.len() == 1 {
        return Some(&candidates[0].1);
    }
    None
}

// endregion

// region: CoerceArg trait and impls

/// Coerce an RValue to a Rust type. Implemented for common R parameter types.
pub trait CoerceArg: Sized {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError>;
}

impl CoerceArg for f64 {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_double_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be numeric", param_name),
                )
            })
    }
}

impl CoerceArg for i64 {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_integer_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be an integer", param_name),
                )
            })
    }
}

impl CoerceArg for usize {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        let i = val
            .as_vector()
            .and_then(|v| v.as_integer_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be a non-negative integer", param_name),
                )
            })?;
        usize::try_from(i).map_err(|_| {
            RError::new(
                RErrorKind::Argument,
                format!("'{}' must be a non-negative integer, got {}", param_name, i),
            )
        })
    }
}

impl CoerceArg for bool {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_logical_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be logical", param_name),
                )
            })
    }
}

impl CoerceArg for String {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector()
            .and_then(|v| v.as_character_scalar())
            .ok_or_else(|| {
                RError::new(
                    RErrorKind::Argument,
                    format!("'{}' must be a character string", param_name),
                )
            })
    }
}

impl CoerceArg for RValue {
    fn coerce(val: &RValue, _param_name: &str) -> Result<Self, RError> {
        Ok(val.clone())
    }
}

impl CoerceArg for Vector {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        val.as_vector().cloned().ok_or_else(|| {
            RError::new(
                RErrorKind::Argument,
                format!("'{}' must be a vector", param_name),
            )
        })
    }
}

impl CoerceArg for Environment {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        match val {
            RValue::Environment(env) => Ok(env.clone()),
            _ => Err(RError::new(
                RErrorKind::Argument,
                format!("'{}' must be an environment", param_name),
            )),
        }
    }
}

/// `Option<T>` coerces the value if present, but returns `None` for NULL.
/// Missing args are handled by the derive (never reach CoerceArg).
impl<T: CoerceArg> CoerceArg for Option<T> {
    fn coerce(val: &RValue, param_name: &str) -> Result<Self, RError> {
        if matches!(val, RValue::Null) {
            return Ok(None);
        }
        T::coerce(val, param_name).map(Some)
    }
}

/// Helper called by `FromArgs` derive-generated code.
pub fn coerce_arg<T: CoerceArg>(val: &RValue, param_name: &str) -> Result<T, RError> {
    T::coerce(val, param_name)
}

/// Helper called by `FromArgs` derive-generated code for `RArg<T>` fields.
/// Produces the three-way Missing/Null/Value from a raw `Option<&RValue>`.
pub fn coerce_arg_three_way<T: CoerceArg>(
    val: Option<&RValue>,
    param_name: &str,
) -> Result<RArg<T>, RError> {
    match val {
        None => Ok(RArg::Missing),
        Some(RValue::Null) => Ok(RArg::Null),
        Some(v) => T::coerce(v, param_name).map(RArg::Value),
    }
}

// endregion
